// Generated by localization/generate_localization.py. Do not edit by hand.
// Edit localization/strings.toml, then run the generator.
package com.rsvpnano.models

object NanoLocales {
    const val DEFAULT = "en"
}
