#!/usr/bin/env python3
"""Regenerate the generation-only reader-font bitmap locality maps."""

from __future__ import annotations

import argparse
from importlib.metadata import version
from pathlib import Path


WORD_FREQ_VERSION = "3.1.1"
UHARFBUZZ_VERSION = "0.56.0"
CODEPOINT_TARGETS = {"ja": "ja", "zh-Hans": "zh"}
GLYPH_TARGETS = {
    "amiri-glyphs": ("ar", "third_party/amiri/Amiri-Regular.ttf"),
    "noto-naskh-arabic-glyphs": (
        "ar",
        "third_party/noto-naskh-arabic/NotoNaskhArabic[wght].ttf",
    ),
}
COMMON_CJK_PUNCTUATION = " \u3000\u3001\u3002\uff0c\uff0e\uff01\uff1f\uff1a\uff1b\u300c\u300d\u300e\u300f\uff08\uff09\uff3b\uff3d\u3010\u3011\u300a\u300b\u3008\u3009\u2026\u2014\u30fb"
COMMON_ARABIC_TEXT = " \u060c\u061b\u061f.!:()[]{}\u00ab\u00bb\u2026\u2014 0123456789 \u0660\u0661\u0662\u0663\u0664\u0665\u0666\u0667\u0668\u0669"
CODEPOINT_CLUSTER_SIZE = 12
CODEPOINT_CLUSTER_RANK_WINDOW = 512
COOCCURRENCE_WORD_LIMIT = 50_000
REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT_ROOT = Path(__file__).resolve().parent / "locality"


def clustered_codepoints(words: object) -> list[int]:
    ordered = dict.fromkeys(map(ord, COMMON_CJK_PUNCTUATION))
    affinities: dict[int, dict[int, int]] = {}
    for rank, word in enumerate(words):
        codepoints = tuple(dict.fromkeys(map(ord, word)))
        for codepoint in codepoints:
            ordered.setdefault(codepoint, None)
        if rank >= COOCCURRENCE_WORD_LIMIT:
            continue
        weight = COOCCURRENCE_WORD_LIMIT - rank
        for index, codepoint in enumerate(codepoints):
            neighbours = affinities.setdefault(codepoint, {})
            for other in codepoints[index + 1:]:
                neighbours[other] = neighbours.get(other, 0) + weight
                reverse = affinities.setdefault(other, {})
                reverse[codepoint] = reverse.get(codepoint, 0) + weight

    ranks = {codepoint: rank for rank, codepoint in enumerate(ordered)}
    remaining = set(ordered)
    result: list[int] = []
    for seed in ordered:
        if seed not in remaining:
            continue
        group = [seed]
        remaining.remove(seed)
        rank_limit = ranks[seed] + CODEPOINT_CLUSTER_RANK_WINDOW
        while len(group) < CODEPOINT_CLUSTER_SIZE:
            candidates = {
                candidate
                for codepoint in group
                for candidate in affinities.get(codepoint, {})
                if candidate in remaining and ranks[candidate] <= rank_limit
            }
            if not candidates:
                break
            candidate = max(
                candidates,
                key=lambda value: (
                    sum(affinities.get(member, {}).get(value, 0) for member in group),
                    -ranks[value],
                ),
            )
            group.append(candidate)
            remaining.remove(candidate)
        result.extend(group)
    return result


def ranked_codepoints(language: str) -> list[int]:
    from wordfreq import iter_wordlist

    return clustered_codepoints(iter_wordlist(language))


def ranked_glyph_ids(language: str, font_path: Path) -> list[int]:
    import uharfbuzz as hb
    from wordfreq import iter_wordlist

    font = hb.Font(hb.Face(font_path.read_bytes()))
    ordered: dict[int, None] = {}

    def add(text: str) -> None:
        buffer = hb.Buffer()
        buffer.add_str(text)
        buffer.direction = "rtl"
        buffer.script = "Arab"
        buffer.language = language
        hb.shape(font, buffer)
        for glyph in buffer.glyph_infos:
            if glyph.codepoint:
                ordered.setdefault(glyph.codepoint, None)

    add(COMMON_ARABIC_TEXT)
    for word in iter_wordlist(language):
        add(word)
    return list(ordered)


def write_values(output: Path, values: list[int], comments: list[str]) -> None:
    lines = comments
    lines.extend(
        " ".join(f"{value:04X}" for value in values[index:index + 16])
        for index in range(0, len(values), 16)
    )
    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {output.relative_to(REPO_ROOT)} ({len(values)} entries)")


def write_codepoint_map(locale: str, language: str) -> None:
    write_values(
        OUTPUT_ROOT / f"{locale}.txt",
        ranked_codepoints(language),
        [
            f"# Generated by fonts/generate_locality_maps.py with wordfreq {WORD_FREQ_VERSION}.",
            f"# Locale: {locale}; source language: {language}; frequency-ranked co-occurrence clusters.",
        ],
    )


def write_glyph_map(name: str, language: str, source: str) -> None:
    write_values(
        OUTPUT_ROOT / f"{name}.txt",
        ranked_glyph_ids(language, REPO_ROOT / source),
        [
            "# Generated by fonts/generate_locality_maps.py with "
            f"wordfreq {WORD_FREQ_VERSION} and uharfbuzz {UHARFBUZZ_VERSION}.",
            f"# Source: {source}; language: {language}; shaped glyph IDs, most common first.",
        ],
    )


def main() -> int:
    targets = CODEPOINT_TARGETS | GLYPH_TARGETS
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("targets", nargs="*", choices=targets, default=tuple(targets))
    args = parser.parse_args()

    for package, required in (("wordfreq", WORD_FREQ_VERSION), ("uharfbuzz", UHARFBUZZ_VERSION)):
        installed = version(package)
        if installed != required:
            parser.error(f"{package} {required} is required, found {installed}")

    for target in args.targets:
        if target in CODEPOINT_TARGETS:
            write_codepoint_map(target, CODEPOINT_TARGETS[target])
        else:
            write_glyph_map(target, *GLYPH_TARGETS[target])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
